services:
  app:
    image: my-app-frontend-dev
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND=./backend/
    container_name: my-app-frontend-dev
  server:
    image: my-app-backend-dev
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    container_name: my-app-backend-dev
  nginx:
    image: nginx:1.20.1
    build: ./frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server